---
# First playbook to resize a vCenter disk.

- name: Resize vCenter disk for virtual machine
  hosts: all
  gather_facts: no
  collections:
    - community.vmware
  vars_files:
    - vars.yml
  vars:
    ansible_python_interpreter: /Users/x.pierre/.virenv/vcenter/bin/python
  tasks:
    - name: Role to resize vCenter disk
      ansible.builtin.import_role:
        name: vcenter_disk
      tags: vcenter


# Second playbook to resize the new disk size on the Linux machine
- name: Resize The Disk on the machine
  hosts: all
  become: true
  remote_user: root
  connection: ssh
  environment:
    PATH: "/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
  vars_files:
    - vars.yml

  tasks:
    - name: Resize Linux Vm disk size
      ansible.builtin.import_role:
        name: linux_disk
      tags: linux
